spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/video-service
    username: local
    password: local
  jpa:
    properties:
      hibernate:
        ddl-auto: update
        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false
  data:
    redis:
      host: localhost
      port: 6379
    mongodb:
      host: localhost
      port: 27017
      database: video-service
      username: local
      password: local
      authentication-database: admin

resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-size: 100
        minimum-number-of-calls: 10
        wait-duration-in-open-state:
          seconds: 20
        failure-rate-threshold: 50
        permitted-number-of-calls-in-half-open-state: 10

external:
  naver:
    url: https://openapi.naver.com
    headers:
      client-id: test
      client-secret: test
  kakao:
    url: https://dapi.kakao.com
    headers:
      rest-api-key: test